= REST API Guide
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
= 개요

[[overview-http-verbs]]
== HTTP 동사

본 REST API에서 사용하는 HTTP 동사(verbs)는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 동사 | 용례

| `GET`
| 리소스를 가져올 때 사용

| `POST`
| 새 리소스를 만들 때 사용

| `PUT`
| 기존 리소스를 수정할 때 사용

| `PATCH`
| 기존 리소스의 일부를 수정할 때 사용

| `DELETE`
| 기존 리소스를 삭제할 떄 사용
|===

[[overview-http-status-codes]]
== HTTP 상태 코드

본 REST API에서 사용하는 HTTP 상태 코드는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 상태 코드 | 용례

| `200 OK`
| 요청을 성공적으로 처리함

| `201 Created`
| 새 리소스를 성공적으로 생성함. 응답의 `Location` 헤더에 해당 리소스의 URI가 담겨있다.

| `204 No Content`
| 기존 리소스를 성공적으로 수정함.

| `400 Bad Request`
| 잘못된 요청을 보낸 경우. 응답 본문에 더 오류에 대한 정보가 담겨있다.

| `404 Not Found`
| 요청한 리소스가 없음.
|===



[[볼 조회]]

|===
| FBallState 값 | Description

| Wait
| 대기

| Play
| 진행

| Finish
| 종료
|===

=== 볼 조회

`GET` 요청을 사용하여 BallUuid 로 Ball 을 조회 할수 있다.

operation::FBallSelect[snippets='response-fields,response-body,request-parameters,http-request']

=== 볼 영향력순 으로 조회

`GET` 요청을 사용하여 영향력 순으로 FBall 을 조회 할수 있다.

operation::ListUpBallListUpOrderByBI[snippets='response-fields,response-body,request-parameters,http-request']

=== Tag를 영향력순 으로 조회

`GET` 요청을 사용하여 검색된 Ball의 Tag를 가져온뒤 Ball의 BI를 통해 순차 정렬을 하여 을 조회 할수 있다.

operation::FTagRankingFromBallInfluencePower[snippets='response-fields,response-body,request-parameters,http-request']

=== Tag를 검색어 기준으로 검색 함 정렬은 TagPower 기준

operation::TagRankingFromTextOrderBySumBI[snippets='response-fields,response-body,request-parameters,http-request']

=== NickName을 검색 정렬을 Player Power

operation::UserNickNameWithFullTextMatchIndex[snippets='response-fields,response-body,request-parameters,http-request']