package com.wing.forutona.AuthDto;

import java.util.Date;

public class Phoneauthtable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PhoneAuthTable.uuid
     *
     * @mbg.generated
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PhoneAuthTable.phonenumber
     *
     * @mbg.generated
     */
    private String phonenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PhoneAuthTable.authnumber
     *
     * @mbg.generated
     */
    private String authnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PhoneAuthTable.UpdateTime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PhoneAuthTable.makeTime
     *
     * @mbg.generated
     */
    private Date maketime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PhoneAuthTable.requestcount
     *
     * @mbg.generated
     */
    private Integer requestcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PhoneAuthTable.IsoCode
     *
     * @mbg.generated
     */
    private String isocode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PhoneAuthTable.uuid
     *
     * @return the value of PhoneAuthTable.uuid
     *
     * @mbg.generated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PhoneAuthTable.uuid
     *
     * @param uuid the value for PhoneAuthTable.uuid
     *
     * @mbg.generated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PhoneAuthTable.phonenumber
     *
     * @return the value of PhoneAuthTable.phonenumber
     *
     * @mbg.generated
     */
    public String getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PhoneAuthTable.phonenumber
     *
     * @param phonenumber the value for PhoneAuthTable.phonenumber
     *
     * @mbg.generated
     */
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber == null ? null : phonenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PhoneAuthTable.authnumber
     *
     * @return the value of PhoneAuthTable.authnumber
     *
     * @mbg.generated
     */
    public String getAuthnumber() {
        return authnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PhoneAuthTable.authnumber
     *
     * @param authnumber the value for PhoneAuthTable.authnumber
     *
     * @mbg.generated
     */
    public void setAuthnumber(String authnumber) {
        this.authnumber = authnumber == null ? null : authnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PhoneAuthTable.UpdateTime
     *
     * @return the value of PhoneAuthTable.UpdateTime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PhoneAuthTable.UpdateTime
     *
     * @param updatetime the value for PhoneAuthTable.UpdateTime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PhoneAuthTable.makeTime
     *
     * @return the value of PhoneAuthTable.makeTime
     *
     * @mbg.generated
     */
    public Date getMaketime() {
        return maketime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PhoneAuthTable.makeTime
     *
     * @param maketime the value for PhoneAuthTable.makeTime
     *
     * @mbg.generated
     */
    public void setMaketime(Date maketime) {
        this.maketime = maketime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PhoneAuthTable.requestcount
     *
     * @return the value of PhoneAuthTable.requestcount
     *
     * @mbg.generated
     */
    public Integer getRequestcount() {
        return requestcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PhoneAuthTable.requestcount
     *
     * @param requestcount the value for PhoneAuthTable.requestcount
     *
     * @mbg.generated
     */
    public void setRequestcount(Integer requestcount) {
        this.requestcount = requestcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PhoneAuthTable.IsoCode
     *
     * @return the value of PhoneAuthTable.IsoCode
     *
     * @mbg.generated
     */
    public String getIsocode() {
        return isocode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PhoneAuthTable.IsoCode
     *
     * @param isocode the value for PhoneAuthTable.IsoCode
     *
     * @mbg.generated
     */
    public void setIsocode(String isocode) {
        this.isocode = isocode == null ? null : isocode.trim();
    }
}