package com.wing.forutona.AuthDto;

import java.util.Date;

public class Userexppointhistroy {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserExpPointHistroy.idx
     *
     * @mbg.generated
     */
    private Integer idx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserExpPointHistroy.Uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserExpPointHistroy.Fromuid
     *
     * @mbg.generated
     */
    private String fromuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserExpPointHistroy.Cubeuuid
     *
     * @mbg.generated
     */
    private String cubeuuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserExpPointHistroy.Points
     *
     * @mbg.generated
     */
    private Double points;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserExpPointHistroy.Explains
     *
     * @mbg.generated
     */
    private String explains;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserExpPointHistroy.GetTime
     *
     * @mbg.generated
     */
    private Date gettime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserExpPointHistroy.DeleteAction
     *
     * @mbg.generated
     */
    private Double deleteaction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserExpPointHistroy.idx
     *
     * @return the value of UserExpPointHistroy.idx
     *
     * @mbg.generated
     */
    public Integer getIdx() {
        return idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserExpPointHistroy.idx
     *
     * @param idx the value for UserExpPointHistroy.idx
     *
     * @mbg.generated
     */
    public void setIdx(Integer idx) {
        this.idx = idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserExpPointHistroy.Uid
     *
     * @return the value of UserExpPointHistroy.Uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserExpPointHistroy.Uid
     *
     * @param uid the value for UserExpPointHistroy.Uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserExpPointHistroy.Fromuid
     *
     * @return the value of UserExpPointHistroy.Fromuid
     *
     * @mbg.generated
     */
    public String getFromuid() {
        return fromuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserExpPointHistroy.Fromuid
     *
     * @param fromuid the value for UserExpPointHistroy.Fromuid
     *
     * @mbg.generated
     */
    public void setFromuid(String fromuid) {
        this.fromuid = fromuid == null ? null : fromuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserExpPointHistroy.Cubeuuid
     *
     * @return the value of UserExpPointHistroy.Cubeuuid
     *
     * @mbg.generated
     */
    public String getCubeuuid() {
        return cubeuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserExpPointHistroy.Cubeuuid
     *
     * @param cubeuuid the value for UserExpPointHistroy.Cubeuuid
     *
     * @mbg.generated
     */
    public void setCubeuuid(String cubeuuid) {
        this.cubeuuid = cubeuuid == null ? null : cubeuuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserExpPointHistroy.Points
     *
     * @return the value of UserExpPointHistroy.Points
     *
     * @mbg.generated
     */
    public Double getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserExpPointHistroy.Points
     *
     * @param points the value for UserExpPointHistroy.Points
     *
     * @mbg.generated
     */
    public void setPoints(Double points) {
        this.points = points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserExpPointHistroy.Explains
     *
     * @return the value of UserExpPointHistroy.Explains
     *
     * @mbg.generated
     */
    public String getExplains() {
        return explains;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserExpPointHistroy.Explains
     *
     * @param explains the value for UserExpPointHistroy.Explains
     *
     * @mbg.generated
     */
    public void setExplains(String explains) {
        this.explains = explains == null ? null : explains.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserExpPointHistroy.GetTime
     *
     * @return the value of UserExpPointHistroy.GetTime
     *
     * @mbg.generated
     */
    public Date getGettime() {
        return gettime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserExpPointHistroy.GetTime
     *
     * @param gettime the value for UserExpPointHistroy.GetTime
     *
     * @mbg.generated
     */
    public void setGettime(Date gettime) {
        this.gettime = gettime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserExpPointHistroy.DeleteAction
     *
     * @return the value of UserExpPointHistroy.DeleteAction
     *
     * @mbg.generated
     */
    public Double getDeleteaction() {
        return deleteaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserExpPointHistroy.DeleteAction
     *
     * @param deleteaction the value for UserExpPointHistroy.DeleteAction
     *
     * @mbg.generated
     */
    public void setDeleteaction(Double deleteaction) {
        this.deleteaction = deleteaction;
    }
}