package com.wing.forutona.FcubeDao;

import com.wing.forutona.FcubeDto.FcubeSponsorSearch;
import com.wing.forutona.FcubeDto.Fcubesponsorextender1;
import java.util.List;

public interface Fcubesponsorextender1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubeSponsorExtender1
     *
     * @mbg.generated
     */
    int insert(Fcubesponsorextender1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubeSponsorExtender1
     *
     * @mbg.generated
     */
    List<Fcubesponsorextender1> selectAll();

    List<Fcubesponsorextender1> selectSponsorForCubeuuid(FcubeSponsorSearch search);
}