package com.wing.forutona.FcubeDao;

import com.wing.forutona.FcubeDto.Fcubeplayer;
import java.util.List;

public interface FcubeplayerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubePlayer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer idx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubePlayer
     *
     * @mbg.generated
     */
    int insert(Fcubeplayer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubePlayer
     *
     * @mbg.generated
     */
    Fcubeplayer selectByPrimaryKey(Integer idx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubePlayer
     *
     * @mbg.generated
     */
    List<Fcubeplayer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubePlayer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Fcubeplayer record);
}