package com.wing.forutona.FcubeDao;

import com.wing.forutona.FcubeDto.FcubeSponsorSearch;
import com.wing.forutona.FcubeDto.Fcubesponsor;
import java.util.List;

public interface FcubesponsorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubeSponsor
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer idx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubeSponsor
     *
     * @mbg.generated
     */
    int insert(Fcubesponsor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubeSponsor
     *
     * @mbg.generated
     */
    Fcubesponsor selectByPrimaryKey(Integer idx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubeSponsor
     *
     * @mbg.generated
     */
    List<Fcubesponsor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubeSponsor
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Fcubesponsor record);

    int selectCubeSponsorSumPointValue(FcubeSponsorSearch search);

    int selectCubeSponsorCount(FcubeSponsorSearch search);
}