package com.wing.forutona.FcubeDao;

import com.wing.forutona.FcubeDto.Fcubequestsuccess;
import java.util.List;

public interface FcubequestsuccessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubeQuestSuccess
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer reqno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubeQuestSuccess
     *
     * @mbg.generated
     */
    int insert(Fcubequestsuccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubeQuestSuccess
     *
     * @mbg.generated
     */
    Fcubequestsuccess selectByPrimaryKey(Integer reqno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubeQuestSuccess
     *
     * @mbg.generated
     */
    List<Fcubequestsuccess> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubeQuestSuccess
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Fcubequestsuccess record);
}