package com.wing.forutona.FcubeDao;

import com.wing.forutona.FcubeDto.Fcubereview;
import java.util.List;

public interface FcubereviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubeReview
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer idx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubeReview
     *
     * @mbg.generated
     */
    int insert(Fcubereview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubeReview
     *
     * @mbg.generated
     */
    Fcubereview selectByPrimaryKey(Integer idx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubeReview
     *
     * @mbg.generated
     */
    List<Fcubereview> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubeReview
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Fcubereview record);

    List<Fcubereview> selectFcubeReview(Fcubereview item);
}