package com.wing.forutona.FcubeDao;

import com.wing.forutona.FcubeDto.FcubeDescirption;
import com.wing.forutona.FcubeDto.Fcubetag;
import java.util.List;

public interface FcubetagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Fcubetag
     *
     * @mbg.generated
     */
    List<Fcubetag> selectAll();

    int inserttags(FcubeDescirption descirption);
}