package com.wing.forutona.FcubeDao;

import com.wing.forutona.FcubeDto.Fcubereply;
import java.util.List;

public interface FcubereplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubeReply
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer commntno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubeReply
     *
     * @mbg.generated
     */
    int insert(Fcubereply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubeReply
     *
     * @mbg.generated
     */
    Fcubereply selectByPrimaryKey(Integer commntno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubeReply
     *
     * @mbg.generated
     */
    List<Fcubereply> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubeReply
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Fcubereply record);
}