package com.wing.forutona.FcubeDao;

import com.wing.forutona.FcubeDto.Fcubecontent;
import java.util.List;

public interface FcubecontentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubeContent
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long idx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubeContent
     *
     * @mbg.generated
     */
    int insert(Fcubecontent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubeContent
     *
     * @mbg.generated
     */
    Fcubecontent selectByPrimaryKey(Long idx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubeContent
     *
     * @mbg.generated
     */
    List<Fcubecontent> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubeContent
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Fcubecontent record);
}