package com.wing.forutona.FcubeDao;

import com.wing.forutona.FcubeDto.Fcubeplayercontent;
import java.util.List;

public interface FcubeplayercontentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubePlayerContent
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer idx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubePlayerContent
     *
     * @mbg.generated
     */
    int insert(Fcubeplayercontent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubePlayerContent
     *
     * @mbg.generated
     */
    Fcubeplayercontent selectByPrimaryKey(Integer idx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubePlayerContent
     *
     * @mbg.generated
     */
    List<Fcubeplayercontent> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubePlayerContent
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Fcubeplayercontent record);
}