package com.wing.forutona.FcubeDao;

import com.wing.forutona.FcubeDto.Mapfindscopestep;
import java.util.List;

public interface MapfindscopestepMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MapFindScopeStep
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer idx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MapFindScopeStep
     *
     * @mbg.generated
     */
    Mapfindscopestep selectByPrimaryKey(Integer idx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MapFindScopeStep
     *
     * @mbg.generated
     */
    List<Mapfindscopestep> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MapFindScopeStep
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Mapfindscopestep record);

    List<Mapfindscopestep> selectAllOrderScopeMeter();
}