package com.wing.forutona.FcubeDao;

import com.wing.forutona.FcubeDto.PlayerjoincubeSearch;
import com.wing.forutona.FcubeDto.Pleyerjoincube;

import java.util.List;

public interface PleyerjoincubeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PleyerJoinCube
     *
     * @mbg.generated
     */
    int insert(Pleyerjoincube record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PleyerJoinCube
     *
     * @mbg.generated
     */
    List<Pleyerjoincube> selectAll();

    List<Pleyerjoincube> getPlayerJoinCubeList(PlayerjoincubeSearch searchitem);
}