package com.wing.forutona.FcubeDto;

import java.util.Date;

public class Fcubereply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeReply.CommntNo
     *
     * @mbg.generated
     */
    private Integer commntno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeReply.Cubeuuid
     *
     * @mbg.generated
     */
    private String cubeuuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeReply.Uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeReply.Bgroup
     *
     * @mbg.generated
     */
    private Integer bgroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeReply.Sorts
     *
     * @mbg.generated
     */
    private Integer sorts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeReply.Depth
     *
     * @mbg.generated
     */
    private Integer depth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeReply.CommntText
     *
     * @mbg.generated
     */
    private String commnttext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeReply.CommntTime
     *
     * @mbg.generated
     */
    private Date commnttime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeReply.CommntNo
     *
     * @return the value of FcubeReply.CommntNo
     *
     * @mbg.generated
     */
    public Integer getCommntno() {
        return commntno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeReply.CommntNo
     *
     * @param commntno the value for FcubeReply.CommntNo
     *
     * @mbg.generated
     */
    public void setCommntno(Integer commntno) {
        this.commntno = commntno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeReply.Cubeuuid
     *
     * @return the value of FcubeReply.Cubeuuid
     *
     * @mbg.generated
     */
    public String getCubeuuid() {
        return cubeuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeReply.Cubeuuid
     *
     * @param cubeuuid the value for FcubeReply.Cubeuuid
     *
     * @mbg.generated
     */
    public void setCubeuuid(String cubeuuid) {
        this.cubeuuid = cubeuuid == null ? null : cubeuuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeReply.Uid
     *
     * @return the value of FcubeReply.Uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeReply.Uid
     *
     * @param uid the value for FcubeReply.Uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeReply.Bgroup
     *
     * @return the value of FcubeReply.Bgroup
     *
     * @mbg.generated
     */
    public Integer getBgroup() {
        return bgroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeReply.Bgroup
     *
     * @param bgroup the value for FcubeReply.Bgroup
     *
     * @mbg.generated
     */
    public void setBgroup(Integer bgroup) {
        this.bgroup = bgroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeReply.Sorts
     *
     * @return the value of FcubeReply.Sorts
     *
     * @mbg.generated
     */
    public Integer getSorts() {
        return sorts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeReply.Sorts
     *
     * @param sorts the value for FcubeReply.Sorts
     *
     * @mbg.generated
     */
    public void setSorts(Integer sorts) {
        this.sorts = sorts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeReply.Depth
     *
     * @return the value of FcubeReply.Depth
     *
     * @mbg.generated
     */
    public Integer getDepth() {
        return depth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeReply.Depth
     *
     * @param depth the value for FcubeReply.Depth
     *
     * @mbg.generated
     */
    public void setDepth(Integer depth) {
        this.depth = depth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeReply.CommntText
     *
     * @return the value of FcubeReply.CommntText
     *
     * @mbg.generated
     */
    public String getCommnttext() {
        return commnttext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeReply.CommntText
     *
     * @param commnttext the value for FcubeReply.CommntText
     *
     * @mbg.generated
     */
    public void setCommnttext(String commnttext) {
        this.commnttext = commnttext == null ? null : commnttext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeReply.CommntTime
     *
     * @return the value of FcubeReply.CommntTime
     *
     * @mbg.generated
     */
    public Date getCommnttime() {
        return commnttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeReply.CommntTime
     *
     * @param commnttime the value for FcubeReply.CommntTime
     *
     * @mbg.generated
     */
    public void setCommnttime(Date commnttime) {
        this.commnttime = commnttime;
    }
}