package com.wing.forutona.FcubeDto;

import java.util.Date;

public class Fcubeplayer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubePlayer.idx
     *
     * @mbg.generated
     */
    private Integer idx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubePlayer.Cubeuuid
     *
     * @mbg.generated
     */
    private String cubeuuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubePlayer.Uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubePlayer.HasLike
     *
     * @mbg.generated
     */
    private Integer haslike;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubePlayer.HasDisLike
     *
     * @mbg.generated
     */
    private Integer hasdislike;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubePlayer.HasGiveup
     *
     * @mbg.generated
     */
    private Integer hasgiveup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubePlayer.HasExit
     *
     * @mbg.generated
     */
    private Integer hasexit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubePlayer.StartTime
     *
     * @mbg.generated
     */
    private Date starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubePlayer.PlayState
     *
     * @mbg.generated
     */
    private Integer playstate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubePlayer.idx
     *
     * @return the value of FcubePlayer.idx
     *
     * @mbg.generated
     */
    public Integer getIdx() {
        return idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubePlayer.idx
     *
     * @param idx the value for FcubePlayer.idx
     *
     * @mbg.generated
     */
    public void setIdx(Integer idx) {
        this.idx = idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubePlayer.Cubeuuid
     *
     * @return the value of FcubePlayer.Cubeuuid
     *
     * @mbg.generated
     */
    public String getCubeuuid() {
        return cubeuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubePlayer.Cubeuuid
     *
     * @param cubeuuid the value for FcubePlayer.Cubeuuid
     *
     * @mbg.generated
     */
    public void setCubeuuid(String cubeuuid) {
        this.cubeuuid = cubeuuid == null ? null : cubeuuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubePlayer.Uid
     *
     * @return the value of FcubePlayer.Uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubePlayer.Uid
     *
     * @param uid the value for FcubePlayer.Uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubePlayer.HasLike
     *
     * @return the value of FcubePlayer.HasLike
     *
     * @mbg.generated
     */
    public Integer getHaslike() {
        return haslike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubePlayer.HasLike
     *
     * @param haslike the value for FcubePlayer.HasLike
     *
     * @mbg.generated
     */
    public void setHaslike(Integer haslike) {
        this.haslike = haslike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubePlayer.HasDisLike
     *
     * @return the value of FcubePlayer.HasDisLike
     *
     * @mbg.generated
     */
    public Integer getHasdislike() {
        return hasdislike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubePlayer.HasDisLike
     *
     * @param hasdislike the value for FcubePlayer.HasDisLike
     *
     * @mbg.generated
     */
    public void setHasdislike(Integer hasdislike) {
        this.hasdislike = hasdislike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubePlayer.HasGiveup
     *
     * @return the value of FcubePlayer.HasGiveup
     *
     * @mbg.generated
     */
    public Integer getHasgiveup() {
        return hasgiveup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubePlayer.HasGiveup
     *
     * @param hasgiveup the value for FcubePlayer.HasGiveup
     *
     * @mbg.generated
     */
    public void setHasgiveup(Integer hasgiveup) {
        this.hasgiveup = hasgiveup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubePlayer.HasExit
     *
     * @return the value of FcubePlayer.HasExit
     *
     * @mbg.generated
     */
    public Integer getHasexit() {
        return hasexit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubePlayer.HasExit
     *
     * @param hasexit the value for FcubePlayer.HasExit
     *
     * @mbg.generated
     */
    public void setHasexit(Integer hasexit) {
        this.hasexit = hasexit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubePlayer.StartTime
     *
     * @return the value of FcubePlayer.StartTime
     *
     * @mbg.generated
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubePlayer.StartTime
     *
     * @param starttime the value for FcubePlayer.StartTime
     *
     * @mbg.generated
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubePlayer.PlayState
     *
     * @return the value of FcubePlayer.PlayState
     *
     * @mbg.generated
     */
    public Integer getPlaystate() {
        return playstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubePlayer.PlayState
     *
     * @param playstate the value for FcubePlayer.PlayState
     *
     * @mbg.generated
     */
    public void setPlaystate(Integer playstate) {
        this.playstate = playstate;
    }
}