package com.wing.forutona.FcubeDto;

public class Fcubequestsuccesscheck {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestSuccessCheck.idx
     *
     * @mbg.generated
     */
    private Integer idx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestSuccessCheck.Cubeuuid
     *
     * @mbg.generated
     */
    private String cubeuuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestSuccessCheck.Uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestSuccessCheck.FromUid
     *
     * @mbg.generated
     */
    private String fromuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestSuccessCheck.ReadUid
     *
     * @mbg.generated
     */
    private String readuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestSuccessCheck.Confirm
     *
     * @mbg.generated
     */
    private Integer confirm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestSuccessCheck.idx
     *
     * @return the value of FcubeQuestSuccessCheck.idx
     *
     * @mbg.generated
     */
    public Integer getIdx() {
        return idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestSuccessCheck.idx
     *
     * @param idx the value for FcubeQuestSuccessCheck.idx
     *
     * @mbg.generated
     */
    public void setIdx(Integer idx) {
        this.idx = idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestSuccessCheck.Cubeuuid
     *
     * @return the value of FcubeQuestSuccessCheck.Cubeuuid
     *
     * @mbg.generated
     */
    public String getCubeuuid() {
        return cubeuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestSuccessCheck.Cubeuuid
     *
     * @param cubeuuid the value for FcubeQuestSuccessCheck.Cubeuuid
     *
     * @mbg.generated
     */
    public void setCubeuuid(String cubeuuid) {
        this.cubeuuid = cubeuuid == null ? null : cubeuuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestSuccessCheck.Uid
     *
     * @return the value of FcubeQuestSuccessCheck.Uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestSuccessCheck.Uid
     *
     * @param uid the value for FcubeQuestSuccessCheck.Uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestSuccessCheck.FromUid
     *
     * @return the value of FcubeQuestSuccessCheck.FromUid
     *
     * @mbg.generated
     */
    public String getFromuid() {
        return fromuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestSuccessCheck.FromUid
     *
     * @param fromuid the value for FcubeQuestSuccessCheck.FromUid
     *
     * @mbg.generated
     */
    public void setFromuid(String fromuid) {
        this.fromuid = fromuid == null ? null : fromuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestSuccessCheck.ReadUid
     *
     * @return the value of FcubeQuestSuccessCheck.ReadUid
     *
     * @mbg.generated
     */
    public String getReaduid() {
        return readuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestSuccessCheck.ReadUid
     *
     * @param readuid the value for FcubeQuestSuccessCheck.ReadUid
     *
     * @mbg.generated
     */
    public void setReaduid(String readuid) {
        this.readuid = readuid == null ? null : readuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestSuccessCheck.Confirm
     *
     * @return the value of FcubeQuestSuccessCheck.Confirm
     *
     * @mbg.generated
     */
    public Integer getConfirm() {
        return confirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestSuccessCheck.Confirm
     *
     * @param confirm the value for FcubeQuestSuccessCheck.Confirm
     *
     * @mbg.generated
     */
    public void setConfirm(Integer confirm) {
        this.confirm = confirm;
    }
}