package com.wing.forutona.FcubeDto;

import java.util.Date;

public class Fcubereply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeReply.CommentNo
     *
     * @mbg.generated
     */
    private Integer commentno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeReply.Cubeuuid
     *
     * @mbg.generated
     */
    private String cubeuuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeReply.Uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeReply.Bgroup
     *
     * @mbg.generated
     */
    private Integer bgroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeReply.Sorts
     *
     * @mbg.generated
     */
    private Integer sorts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeReply.Depth
     *
     * @mbg.generated
     */
    private Integer depth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeReply.CommentText
     *
     * @mbg.generated
     */
    private String commenttext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeReply.CommentTime
     *
     * @mbg.generated
     */
    private Date commenttime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeReply.CommentNo
     *
     * @return the value of FcubeReply.CommentNo
     *
     * @mbg.generated
     */
    public Integer getCommentno() {
        return commentno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeReply.CommentNo
     *
     * @param commentno the value for FcubeReply.CommentNo
     *
     * @mbg.generated
     */
    public void setCommentno(Integer commentno) {
        this.commentno = commentno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeReply.Cubeuuid
     *
     * @return the value of FcubeReply.Cubeuuid
     *
     * @mbg.generated
     */
    public String getCubeuuid() {
        return cubeuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeReply.Cubeuuid
     *
     * @param cubeuuid the value for FcubeReply.Cubeuuid
     *
     * @mbg.generated
     */
    public void setCubeuuid(String cubeuuid) {
        this.cubeuuid = cubeuuid == null ? null : cubeuuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeReply.Uid
     *
     * @return the value of FcubeReply.Uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeReply.Uid
     *
     * @param uid the value for FcubeReply.Uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeReply.Bgroup
     *
     * @return the value of FcubeReply.Bgroup
     *
     * @mbg.generated
     */
    public Integer getBgroup() {
        return bgroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeReply.Bgroup
     *
     * @param bgroup the value for FcubeReply.Bgroup
     *
     * @mbg.generated
     */
    public void setBgroup(Integer bgroup) {
        this.bgroup = bgroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeReply.Sorts
     *
     * @return the value of FcubeReply.Sorts
     *
     * @mbg.generated
     */
    public Integer getSorts() {
        return sorts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeReply.Sorts
     *
     * @param sorts the value for FcubeReply.Sorts
     *
     * @mbg.generated
     */
    public void setSorts(Integer sorts) {
        this.sorts = sorts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeReply.Depth
     *
     * @return the value of FcubeReply.Depth
     *
     * @mbg.generated
     */
    public Integer getDepth() {
        return depth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeReply.Depth
     *
     * @param depth the value for FcubeReply.Depth
     *
     * @mbg.generated
     */
    public void setDepth(Integer depth) {
        this.depth = depth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeReply.CommentText
     *
     * @return the value of FcubeReply.CommentText
     *
     * @mbg.generated
     */
    public String getCommenttext() {
        return commenttext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeReply.CommentText
     *
     * @param commenttext the value for FcubeReply.CommentText
     *
     * @mbg.generated
     */
    public void setCommenttext(String commenttext) {
        this.commenttext = commenttext == null ? null : commenttext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeReply.CommentTime
     *
     * @return the value of FcubeReply.CommentTime
     *
     * @mbg.generated
     */
    public Date getCommenttime() {
        return commenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeReply.CommentTime
     *
     * @param commenttime the value for FcubeReply.CommentTime
     *
     * @mbg.generated
     */
    public void setCommenttime(Date commenttime) {
        this.commenttime = commenttime;
    }
}