package com.wing.forutona.FcubeDto;

import java.util.Date;

public class Fcubequestsuccess {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestSuccess.reqno
     *
     * @mbg.generated
     */
    private Integer reqno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestSuccess.Cubeuuid
     *
     * @mbg.generated
     */
    private String cubeuuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestSuccess.Uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestSuccess.FromUid
     *
     * @mbg.generated
     */
    private String fromuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestSuccess.ContentType
     *
     * @mbg.generated
     */
    private String contenttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestSuccess.ReadingCheck
     *
     * @mbg.generated
     */
    private Integer readingcheck;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestSuccess.ScuessCheck
     *
     * @mbg.generated
     */
    private Integer scuesscheck;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestSuccess.ReqTime
     *
     * @mbg.generated
     */
    private Date reqtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestSuccess.JudgmentTime
     *
     * @mbg.generated
     */
    private Date judgmenttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestSuccess.Content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestSuccess.reqno
     *
     * @return the value of FcubeQuestSuccess.reqno
     *
     * @mbg.generated
     */
    public Integer getReqno() {
        return reqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestSuccess.reqno
     *
     * @param reqno the value for FcubeQuestSuccess.reqno
     *
     * @mbg.generated
     */
    public void setReqno(Integer reqno) {
        this.reqno = reqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestSuccess.Cubeuuid
     *
     * @return the value of FcubeQuestSuccess.Cubeuuid
     *
     * @mbg.generated
     */
    public String getCubeuuid() {
        return cubeuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestSuccess.Cubeuuid
     *
     * @param cubeuuid the value for FcubeQuestSuccess.Cubeuuid
     *
     * @mbg.generated
     */
    public void setCubeuuid(String cubeuuid) {
        this.cubeuuid = cubeuuid == null ? null : cubeuuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestSuccess.Uid
     *
     * @return the value of FcubeQuestSuccess.Uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestSuccess.Uid
     *
     * @param uid the value for FcubeQuestSuccess.Uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestSuccess.FromUid
     *
     * @return the value of FcubeQuestSuccess.FromUid
     *
     * @mbg.generated
     */
    public String getFromuid() {
        return fromuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestSuccess.FromUid
     *
     * @param fromuid the value for FcubeQuestSuccess.FromUid
     *
     * @mbg.generated
     */
    public void setFromuid(String fromuid) {
        this.fromuid = fromuid == null ? null : fromuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestSuccess.ContentType
     *
     * @return the value of FcubeQuestSuccess.ContentType
     *
     * @mbg.generated
     */
    public String getContenttype() {
        return contenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestSuccess.ContentType
     *
     * @param contenttype the value for FcubeQuestSuccess.ContentType
     *
     * @mbg.generated
     */
    public void setContenttype(String contenttype) {
        this.contenttype = contenttype == null ? null : contenttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestSuccess.ReadingCheck
     *
     * @return the value of FcubeQuestSuccess.ReadingCheck
     *
     * @mbg.generated
     */
    public Integer getReadingcheck() {
        return readingcheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestSuccess.ReadingCheck
     *
     * @param readingcheck the value for FcubeQuestSuccess.ReadingCheck
     *
     * @mbg.generated
     */
    public void setReadingcheck(Integer readingcheck) {
        this.readingcheck = readingcheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestSuccess.ScuessCheck
     *
     * @return the value of FcubeQuestSuccess.ScuessCheck
     *
     * @mbg.generated
     */
    public Integer getScuesscheck() {
        return scuesscheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestSuccess.ScuessCheck
     *
     * @param scuesscheck the value for FcubeQuestSuccess.ScuessCheck
     *
     * @mbg.generated
     */
    public void setScuesscheck(Integer scuesscheck) {
        this.scuesscheck = scuesscheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestSuccess.ReqTime
     *
     * @return the value of FcubeQuestSuccess.ReqTime
     *
     * @mbg.generated
     */
    public Date getReqtime() {
        return reqtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestSuccess.ReqTime
     *
     * @param reqtime the value for FcubeQuestSuccess.ReqTime
     *
     * @mbg.generated
     */
    public void setReqtime(Date reqtime) {
        this.reqtime = reqtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestSuccess.JudgmentTime
     *
     * @return the value of FcubeQuestSuccess.JudgmentTime
     *
     * @mbg.generated
     */
    public Date getJudgmenttime() {
        return judgmenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestSuccess.JudgmentTime
     *
     * @param judgmenttime the value for FcubeQuestSuccess.JudgmentTime
     *
     * @mbg.generated
     */
    public void setJudgmenttime(Date judgmenttime) {
        this.judgmenttime = judgmenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestSuccess.Content
     *
     * @return the value of FcubeQuestSuccess.Content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestSuccess.Content
     *
     * @param content the value for FcubeQuestSuccess.Content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}