package com.wing.forutona.FcubeDto;

import java.util.Date;

public class Fcubeplayercontent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubePlayerContent.idx
     *
     * @mbg.generated
     */
    private Integer idx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubePlayerContent.Cubeuuid
     *
     * @mbg.generated
     */
    private String cubeuuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubePlayerContent.Uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubePlayerContent.ContentType
     *
     * @mbg.generated
     */
    private String contenttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubePlayerContent.ContentUpdateTime
     *
     * @mbg.generated
     */
    private Date contentupdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubePlayerContent.ContentValue
     *
     * @mbg.generated
     */
    private String contentvalue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubePlayerContent.idx
     *
     * @return the value of FcubePlayerContent.idx
     *
     * @mbg.generated
     */
    public Integer getIdx() {
        return idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubePlayerContent.idx
     *
     * @param idx the value for FcubePlayerContent.idx
     *
     * @mbg.generated
     */
    public void setIdx(Integer idx) {
        this.idx = idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubePlayerContent.Cubeuuid
     *
     * @return the value of FcubePlayerContent.Cubeuuid
     *
     * @mbg.generated
     */
    public String getCubeuuid() {
        return cubeuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubePlayerContent.Cubeuuid
     *
     * @param cubeuuid the value for FcubePlayerContent.Cubeuuid
     *
     * @mbg.generated
     */
    public void setCubeuuid(String cubeuuid) {
        this.cubeuuid = cubeuuid == null ? null : cubeuuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubePlayerContent.Uid
     *
     * @return the value of FcubePlayerContent.Uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubePlayerContent.Uid
     *
     * @param uid the value for FcubePlayerContent.Uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubePlayerContent.ContentType
     *
     * @return the value of FcubePlayerContent.ContentType
     *
     * @mbg.generated
     */
    public String getContenttype() {
        return contenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubePlayerContent.ContentType
     *
     * @param contenttype the value for FcubePlayerContent.ContentType
     *
     * @mbg.generated
     */
    public void setContenttype(String contenttype) {
        this.contenttype = contenttype == null ? null : contenttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubePlayerContent.ContentUpdateTime
     *
     * @return the value of FcubePlayerContent.ContentUpdateTime
     *
     * @mbg.generated
     */
    public Date getContentupdatetime() {
        return contentupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubePlayerContent.ContentUpdateTime
     *
     * @param contentupdatetime the value for FcubePlayerContent.ContentUpdateTime
     *
     * @mbg.generated
     */
    public void setContentupdatetime(Date contentupdatetime) {
        this.contentupdatetime = contentupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubePlayerContent.ContentValue
     *
     * @return the value of FcubePlayerContent.ContentValue
     *
     * @mbg.generated
     */
    public String getContentvalue() {
        return contentvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubePlayerContent.ContentValue
     *
     * @param contentvalue the value for FcubePlayerContent.ContentValue
     *
     * @mbg.generated
     */
    public void setContentvalue(String contentvalue) {
        this.contentvalue = contentvalue == null ? null : contentvalue.trim();
    }
}