package com.wing.forutona.FcubeDto;

public class Fcubereview {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeReview.idx
     *
     * @mbg.generated
     */
    private Integer idx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeReview.Cubeuuid
     *
     * @mbg.generated
     */
    private String cubeuuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeReview.Uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeReview.toMakerComment
     *
     * @mbg.generated
     */
    private String tomakercomment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeReview.StarPoint
     *
     * @mbg.generated
     */
    private Double starpoint;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeReview.idx
     *
     * @return the value of FcubeReview.idx
     *
     * @mbg.generated
     */
    public Integer getIdx() {
        return idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeReview.idx
     *
     * @param idx the value for FcubeReview.idx
     *
     * @mbg.generated
     */
    public void setIdx(Integer idx) {
        this.idx = idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeReview.Cubeuuid
     *
     * @return the value of FcubeReview.Cubeuuid
     *
     * @mbg.generated
     */
    public String getCubeuuid() {
        return cubeuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeReview.Cubeuuid
     *
     * @param cubeuuid the value for FcubeReview.Cubeuuid
     *
     * @mbg.generated
     */
    public void setCubeuuid(String cubeuuid) {
        this.cubeuuid = cubeuuid == null ? null : cubeuuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeReview.Uid
     *
     * @return the value of FcubeReview.Uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeReview.Uid
     *
     * @param uid the value for FcubeReview.Uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeReview.toMakerComment
     *
     * @return the value of FcubeReview.toMakerComment
     *
     * @mbg.generated
     */
    public String getTomakercomment() {
        return tomakercomment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeReview.toMakerComment
     *
     * @param tomakercomment the value for FcubeReview.toMakerComment
     *
     * @mbg.generated
     */
    public void setTomakercomment(String tomakercomment) {
        this.tomakercomment = tomakercomment == null ? null : tomakercomment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeReview.StarPoint
     *
     * @return the value of FcubeReview.StarPoint
     *
     * @mbg.generated
     */
    public Double getStarpoint() {
        return starpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeReview.StarPoint
     *
     * @param starpoint the value for FcubeReview.StarPoint
     *
     * @mbg.generated
     */
    public void setStarpoint(Double starpoint) {
        this.starpoint = starpoint;
    }
}