package com.wing.forutona.FcubeDto;

import java.util.Date;

public class Fcubesponsor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeSponsor.idx
     *
     * @mbg.generated
     */
    private Integer idx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeSponsor.cubeuuid
     *
     * @mbg.generated
     */
    private String cubeuuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeSponsor.uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeSponsor.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeSponsor.sendTime
     *
     * @mbg.generated
     */
    private Date sendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeSponsor.pointType
     *
     * @mbg.generated
     */
    private String pointType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeSponsor.pointValue
     *
     * @mbg.generated
     */
    private Integer pointValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeSponsor.idx
     *
     * @return the value of FcubeSponsor.idx
     *
     * @mbg.generated
     */
    public Integer getIdx() {
        return idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeSponsor.idx
     *
     * @param idx the value for FcubeSponsor.idx
     *
     * @mbg.generated
     */
    public void setIdx(Integer idx) {
        this.idx = idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeSponsor.cubeuuid
     *
     * @return the value of FcubeSponsor.cubeuuid
     *
     * @mbg.generated
     */
    public String getCubeuuid() {
        return cubeuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeSponsor.cubeuuid
     *
     * @param cubeuuid the value for FcubeSponsor.cubeuuid
     *
     * @mbg.generated
     */
    public void setCubeuuid(String cubeuuid) {
        this.cubeuuid = cubeuuid == null ? null : cubeuuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeSponsor.uid
     *
     * @return the value of FcubeSponsor.uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeSponsor.uid
     *
     * @param uid the value for FcubeSponsor.uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeSponsor.comment
     *
     * @return the value of FcubeSponsor.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeSponsor.comment
     *
     * @param comment the value for FcubeSponsor.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeSponsor.sendTime
     *
     * @return the value of FcubeSponsor.sendTime
     *
     * @mbg.generated
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeSponsor.sendTime
     *
     * @param sendTime the value for FcubeSponsor.sendTime
     *
     * @mbg.generated
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeSponsor.pointType
     *
     * @return the value of FcubeSponsor.pointType
     *
     * @mbg.generated
     */
    public String getPointType() {
        return pointType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeSponsor.pointType
     *
     * @param pointType the value for FcubeSponsor.pointType
     *
     * @mbg.generated
     */
    public void setPointType(String pointType) {
        this.pointType = pointType == null ? null : pointType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeSponsor.pointValue
     *
     * @return the value of FcubeSponsor.pointValue
     *
     * @mbg.generated
     */
    public Integer getPointValue() {
        return pointValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeSponsor.pointValue
     *
     * @param pointValue the value for FcubeSponsor.pointValue
     *
     * @mbg.generated
     */
    public void setPointValue(Integer pointValue) {
        this.pointValue = pointValue;
    }
}