package com.wing.forutona.FcubeDto;

import java.util.Date;

public class Fcubesponsorextender1 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeSponsorExtender1.cubeuuid
     *
     * @mbg.generated
     */
    private String cubeuuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeSponsorExtender1.uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeSponsorExtender1.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeSponsorExtender1.sendTime
     *
     * @mbg.generated
     */
    private Date sendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeSponsorExtender1.pointType
     *
     * @mbg.generated
     */
    private String pointType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeSponsorExtender1.pointValue
     *
     * @mbg.generated
     */
    private Integer pointValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeSponsorExtender1.NickName
     *
     * @mbg.generated
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeSponsorExtender1.ProfilePicktureUrl
     *
     * @mbg.generated
     */
    private String profilePicktureUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeSponsorExtender1.UserLevel
     *
     * @mbg.generated
     */
    private Double userLevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeSponsorExtender1.cubeuuid
     *
     * @return the value of FcubeSponsorExtender1.cubeuuid
     *
     * @mbg.generated
     */
    public String getCubeuuid() {
        return cubeuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeSponsorExtender1.cubeuuid
     *
     * @param cubeuuid the value for FcubeSponsorExtender1.cubeuuid
     *
     * @mbg.generated
     */
    public void setCubeuuid(String cubeuuid) {
        this.cubeuuid = cubeuuid == null ? null : cubeuuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeSponsorExtender1.uid
     *
     * @return the value of FcubeSponsorExtender1.uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeSponsorExtender1.uid
     *
     * @param uid the value for FcubeSponsorExtender1.uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeSponsorExtender1.comment
     *
     * @return the value of FcubeSponsorExtender1.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeSponsorExtender1.comment
     *
     * @param comment the value for FcubeSponsorExtender1.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeSponsorExtender1.sendTime
     *
     * @return the value of FcubeSponsorExtender1.sendTime
     *
     * @mbg.generated
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeSponsorExtender1.sendTime
     *
     * @param sendTime the value for FcubeSponsorExtender1.sendTime
     *
     * @mbg.generated
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeSponsorExtender1.pointType
     *
     * @return the value of FcubeSponsorExtender1.pointType
     *
     * @mbg.generated
     */
    public String getPointType() {
        return pointType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeSponsorExtender1.pointType
     *
     * @param pointType the value for FcubeSponsorExtender1.pointType
     *
     * @mbg.generated
     */
    public void setPointType(String pointType) {
        this.pointType = pointType == null ? null : pointType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeSponsorExtender1.pointValue
     *
     * @return the value of FcubeSponsorExtender1.pointValue
     *
     * @mbg.generated
     */
    public Integer getPointValue() {
        return pointValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeSponsorExtender1.pointValue
     *
     * @param pointValue the value for FcubeSponsorExtender1.pointValue
     *
     * @mbg.generated
     */
    public void setPointValue(Integer pointValue) {
        this.pointValue = pointValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeSponsorExtender1.NickName
     *
     * @return the value of FcubeSponsorExtender1.NickName
     *
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeSponsorExtender1.NickName
     *
     * @param nickName the value for FcubeSponsorExtender1.NickName
     *
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeSponsorExtender1.ProfilePicktureUrl
     *
     * @return the value of FcubeSponsorExtender1.ProfilePicktureUrl
     *
     * @mbg.generated
     */
    public String getProfilePicktureUrl() {
        return profilePicktureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeSponsorExtender1.ProfilePicktureUrl
     *
     * @param profilePicktureUrl the value for FcubeSponsorExtender1.ProfilePicktureUrl
     *
     * @mbg.generated
     */
    public void setProfilePicktureUrl(String profilePicktureUrl) {
        this.profilePicktureUrl = profilePicktureUrl == null ? null : profilePicktureUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeSponsorExtender1.UserLevel
     *
     * @return the value of FcubeSponsorExtender1.UserLevel
     *
     * @mbg.generated
     */
    public Double getUserLevel() {
        return userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeSponsorExtender1.UserLevel
     *
     * @param userLevel the value for FcubeSponsorExtender1.UserLevel
     *
     * @mbg.generated
     */
    public void setUserLevel(Double userLevel) {
        this.userLevel = userLevel;
    }
}