package com.wing.forutona.FcubeDto;

import java.util.Date;

public class Fcube {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.Cubeuuid
     *
     * @mbg.generated
     */
    private String cubeuuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.Uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.longitude
     *
     * @mbg.generated
     */
    private Double longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.latitude
     *
     * @mbg.generated
     */
    private Double latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.CubeName
     *
     * @mbg.generated
     */
    private String cubename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.CubeType
     *
     * @mbg.generated
     */
    private String cubetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.MakeTime
     *
     * @mbg.generated
     */
    private Date maketime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.Influence
     *
     * @mbg.generated
     */
    private Double influence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.CubeState
     *
     * @mbg.generated
     */
    private Integer cubestate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.PlaceAddress
     *
     * @mbg.generated
     */
    private String placeaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.AdministrativeArea
     *
     * @mbg.generated
     */
    private String administrativearea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.Country
     *
     * @mbg.generated
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.NaPoint
     *
     * @mbg.generated
     */
    private Double napoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.YouPoint
     *
     * @mbg.generated
     */
    private Double youpoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.PointReward
     *
     * @mbg.generated
     */
    private Double pointreward;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.InfluenceReward
     *
     * @mbg.generated
     */
    private Double influencereward;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.ActivationTime
     *
     * @mbg.generated
     */
    private Date activationtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.CubePassword
     *
     * @mbg.generated
     */
    private String cubepassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.HasPassword
     *
     * @mbg.generated
     */
    private Integer haspassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.CubeScope
     *
     * @mbg.generated
     */
    private Integer cubescope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.InfluenceLevel
     *
     * @mbg.generated
     */
    private Double influencelevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.CubeHits
     *
     * @mbg.generated
     */
    private Integer cubehits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.CubeLikes
     *
     * @mbg.generated
     */
    private Integer cubelikes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.CubeDisLikes
     *
     * @mbg.generated
     */
    private Integer cubedislikes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.ballPower
     *
     * @mbg.generated
     */
    private Integer ballpower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.JoinPlayer
     *
     * @mbg.generated
     */
    private Integer joinplayer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.MaximumPlayers
     *
     * @mbg.generated
     */
    private Integer maximumplayers;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.StarPoints
     *
     * @mbg.generated
     */
    private Double starpoints;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.ExpGiveFlag
     *
     * @mbg.generated
     */
    private Integer expgiveflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.MakeExp
     *
     * @mbg.generated
     */
    private Double makeexp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.CommentCount
     *
     * @mbg.generated
     */
    private Integer commentcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.UserExp
     *
     * @mbg.generated
     */
    private Double userexp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.placePoint
     *
     * @mbg.generated
     */
    private byte[] placepoint;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.Cubeuuid
     *
     * @return the value of Fcube.Cubeuuid
     *
     * @mbg.generated
     */
    public String getCubeuuid() {
        return cubeuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.Cubeuuid
     *
     * @param cubeuuid the value for Fcube.Cubeuuid
     *
     * @mbg.generated
     */
    public void setCubeuuid(String cubeuuid) {
        this.cubeuuid = cubeuuid == null ? null : cubeuuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.Uid
     *
     * @return the value of Fcube.Uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.Uid
     *
     * @param uid the value for Fcube.Uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.longitude
     *
     * @return the value of Fcube.longitude
     *
     * @mbg.generated
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.longitude
     *
     * @param longitude the value for Fcube.longitude
     *
     * @mbg.generated
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.latitude
     *
     * @return the value of Fcube.latitude
     *
     * @mbg.generated
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.latitude
     *
     * @param latitude the value for Fcube.latitude
     *
     * @mbg.generated
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.CubeName
     *
     * @return the value of Fcube.CubeName
     *
     * @mbg.generated
     */
    public String getCubename() {
        return cubename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.CubeName
     *
     * @param cubename the value for Fcube.CubeName
     *
     * @mbg.generated
     */
    public void setCubename(String cubename) {
        this.cubename = cubename == null ? null : cubename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.CubeType
     *
     * @return the value of Fcube.CubeType
     *
     * @mbg.generated
     */
    public String getCubetype() {
        return cubetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.CubeType
     *
     * @param cubetype the value for Fcube.CubeType
     *
     * @mbg.generated
     */
    public void setCubetype(String cubetype) {
        this.cubetype = cubetype == null ? null : cubetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.MakeTime
     *
     * @return the value of Fcube.MakeTime
     *
     * @mbg.generated
     */
    public Date getMaketime() {
        return maketime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.MakeTime
     *
     * @param maketime the value for Fcube.MakeTime
     *
     * @mbg.generated
     */
    public void setMaketime(Date maketime) {
        this.maketime = maketime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.Influence
     *
     * @return the value of Fcube.Influence
     *
     * @mbg.generated
     */
    public Double getInfluence() {
        return influence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.Influence
     *
     * @param influence the value for Fcube.Influence
     *
     * @mbg.generated
     */
    public void setInfluence(Double influence) {
        this.influence = influence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.CubeState
     *
     * @return the value of Fcube.CubeState
     *
     * @mbg.generated
     */
    public Integer getCubestate() {
        return cubestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.CubeState
     *
     * @param cubestate the value for Fcube.CubeState
     *
     * @mbg.generated
     */
    public void setCubestate(Integer cubestate) {
        this.cubestate = cubestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.PlaceAddress
     *
     * @return the value of Fcube.PlaceAddress
     *
     * @mbg.generated
     */
    public String getPlaceaddress() {
        return placeaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.PlaceAddress
     *
     * @param placeaddress the value for Fcube.PlaceAddress
     *
     * @mbg.generated
     */
    public void setPlaceaddress(String placeaddress) {
        this.placeaddress = placeaddress == null ? null : placeaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.AdministrativeArea
     *
     * @return the value of Fcube.AdministrativeArea
     *
     * @mbg.generated
     */
    public String getAdministrativearea() {
        return administrativearea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.AdministrativeArea
     *
     * @param administrativearea the value for Fcube.AdministrativeArea
     *
     * @mbg.generated
     */
    public void setAdministrativearea(String administrativearea) {
        this.administrativearea = administrativearea == null ? null : administrativearea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.Country
     *
     * @return the value of Fcube.Country
     *
     * @mbg.generated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.Country
     *
     * @param country the value for Fcube.Country
     *
     * @mbg.generated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.NaPoint
     *
     * @return the value of Fcube.NaPoint
     *
     * @mbg.generated
     */
    public Double getNapoint() {
        return napoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.NaPoint
     *
     * @param napoint the value for Fcube.NaPoint
     *
     * @mbg.generated
     */
    public void setNapoint(Double napoint) {
        this.napoint = napoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.YouPoint
     *
     * @return the value of Fcube.YouPoint
     *
     * @mbg.generated
     */
    public Double getYoupoint() {
        return youpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.YouPoint
     *
     * @param youpoint the value for Fcube.YouPoint
     *
     * @mbg.generated
     */
    public void setYoupoint(Double youpoint) {
        this.youpoint = youpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.PointReward
     *
     * @return the value of Fcube.PointReward
     *
     * @mbg.generated
     */
    public Double getPointreward() {
        return pointreward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.PointReward
     *
     * @param pointreward the value for Fcube.PointReward
     *
     * @mbg.generated
     */
    public void setPointreward(Double pointreward) {
        this.pointreward = pointreward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.InfluenceReward
     *
     * @return the value of Fcube.InfluenceReward
     *
     * @mbg.generated
     */
    public Double getInfluencereward() {
        return influencereward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.InfluenceReward
     *
     * @param influencereward the value for Fcube.InfluenceReward
     *
     * @mbg.generated
     */
    public void setInfluencereward(Double influencereward) {
        this.influencereward = influencereward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.ActivationTime
     *
     * @return the value of Fcube.ActivationTime
     *
     * @mbg.generated
     */
    public Date getActivationtime() {
        return activationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.ActivationTime
     *
     * @param activationtime the value for Fcube.ActivationTime
     *
     * @mbg.generated
     */
    public void setActivationtime(Date activationtime) {
        this.activationtime = activationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.CubePassword
     *
     * @return the value of Fcube.CubePassword
     *
     * @mbg.generated
     */
    public String getCubepassword() {
        return cubepassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.CubePassword
     *
     * @param cubepassword the value for Fcube.CubePassword
     *
     * @mbg.generated
     */
    public void setCubepassword(String cubepassword) {
        this.cubepassword = cubepassword == null ? null : cubepassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.HasPassword
     *
     * @return the value of Fcube.HasPassword
     *
     * @mbg.generated
     */
    public Integer getHaspassword() {
        return haspassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.HasPassword
     *
     * @param haspassword the value for Fcube.HasPassword
     *
     * @mbg.generated
     */
    public void setHaspassword(Integer haspassword) {
        this.haspassword = haspassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.CubeScope
     *
     * @return the value of Fcube.CubeScope
     *
     * @mbg.generated
     */
    public Integer getCubescope() {
        return cubescope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.CubeScope
     *
     * @param cubescope the value for Fcube.CubeScope
     *
     * @mbg.generated
     */
    public void setCubescope(Integer cubescope) {
        this.cubescope = cubescope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.InfluenceLevel
     *
     * @return the value of Fcube.InfluenceLevel
     *
     * @mbg.generated
     */
    public Double getInfluencelevel() {
        return influencelevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.InfluenceLevel
     *
     * @param influencelevel the value for Fcube.InfluenceLevel
     *
     * @mbg.generated
     */
    public void setInfluencelevel(Double influencelevel) {
        this.influencelevel = influencelevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.CubeHits
     *
     * @return the value of Fcube.CubeHits
     *
     * @mbg.generated
     */
    public Integer getCubehits() {
        return cubehits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.CubeHits
     *
     * @param cubehits the value for Fcube.CubeHits
     *
     * @mbg.generated
     */
    public void setCubehits(Integer cubehits) {
        this.cubehits = cubehits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.CubeLikes
     *
     * @return the value of Fcube.CubeLikes
     *
     * @mbg.generated
     */
    public Integer getCubelikes() {
        return cubelikes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.CubeLikes
     *
     * @param cubelikes the value for Fcube.CubeLikes
     *
     * @mbg.generated
     */
    public void setCubelikes(Integer cubelikes) {
        this.cubelikes = cubelikes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.CubeDisLikes
     *
     * @return the value of Fcube.CubeDisLikes
     *
     * @mbg.generated
     */
    public Integer getCubedislikes() {
        return cubedislikes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.CubeDisLikes
     *
     * @param cubedislikes the value for Fcube.CubeDisLikes
     *
     * @mbg.generated
     */
    public void setCubedislikes(Integer cubedislikes) {
        this.cubedislikes = cubedislikes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.ballPower
     *
     * @return the value of Fcube.ballPower
     *
     * @mbg.generated
     */
    public Integer getBallpower() {
        return ballpower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.ballPower
     *
     * @param ballpower the value for Fcube.ballPower
     *
     * @mbg.generated
     */
    public void setBallpower(Integer ballpower) {
        this.ballpower = ballpower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.JoinPlayer
     *
     * @return the value of Fcube.JoinPlayer
     *
     * @mbg.generated
     */
    public Integer getJoinplayer() {
        return joinplayer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.JoinPlayer
     *
     * @param joinplayer the value for Fcube.JoinPlayer
     *
     * @mbg.generated
     */
    public void setJoinplayer(Integer joinplayer) {
        this.joinplayer = joinplayer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.MaximumPlayers
     *
     * @return the value of Fcube.MaximumPlayers
     *
     * @mbg.generated
     */
    public Integer getMaximumplayers() {
        return maximumplayers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.MaximumPlayers
     *
     * @param maximumplayers the value for Fcube.MaximumPlayers
     *
     * @mbg.generated
     */
    public void setMaximumplayers(Integer maximumplayers) {
        this.maximumplayers = maximumplayers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.StarPoints
     *
     * @return the value of Fcube.StarPoints
     *
     * @mbg.generated
     */
    public Double getStarpoints() {
        return starpoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.StarPoints
     *
     * @param starpoints the value for Fcube.StarPoints
     *
     * @mbg.generated
     */
    public void setStarpoints(Double starpoints) {
        this.starpoints = starpoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.ExpGiveFlag
     *
     * @return the value of Fcube.ExpGiveFlag
     *
     * @mbg.generated
     */
    public Integer getExpgiveflag() {
        return expgiveflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.ExpGiveFlag
     *
     * @param expgiveflag the value for Fcube.ExpGiveFlag
     *
     * @mbg.generated
     */
    public void setExpgiveflag(Integer expgiveflag) {
        this.expgiveflag = expgiveflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.MakeExp
     *
     * @return the value of Fcube.MakeExp
     *
     * @mbg.generated
     */
    public Double getMakeexp() {
        return makeexp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.MakeExp
     *
     * @param makeexp the value for Fcube.MakeExp
     *
     * @mbg.generated
     */
    public void setMakeexp(Double makeexp) {
        this.makeexp = makeexp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.CommentCount
     *
     * @return the value of Fcube.CommentCount
     *
     * @mbg.generated
     */
    public Integer getCommentcount() {
        return commentcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.CommentCount
     *
     * @param commentcount the value for Fcube.CommentCount
     *
     * @mbg.generated
     */
    public void setCommentcount(Integer commentcount) {
        this.commentcount = commentcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.UserExp
     *
     * @return the value of Fcube.UserExp
     *
     * @mbg.generated
     */
    public Double getUserexp() {
        return userexp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.UserExp
     *
     * @param userexp the value for Fcube.UserExp
     *
     * @mbg.generated
     */
    public void setUserexp(Double userexp) {
        this.userexp = userexp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.placePoint
     *
     * @return the value of Fcube.placePoint
     *
     * @mbg.generated
     */
    public byte[] getPlacepoint() {
        return placepoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.placePoint
     *
     * @param placepoint the value for Fcube.placePoint
     *
     * @mbg.generated
     */
    public void setPlacepoint(byte[] placepoint) {
        this.placepoint = placepoint;
    }
}