package com.wing.forutona.FcubeDto;

import java.util.Date;

public class Fcubetagextender1 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubetagExtender1.cubeuuid
     *
     * @mbg.generated
     */
    private String cubeuuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubetagExtender1.tagitem
     *
     * @mbg.generated
     */
    private String tagitem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubetagExtender1.Uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubetagExtender1.longitude
     *
     * @mbg.generated
     */
    private Double longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubetagExtender1.latitude
     *
     * @mbg.generated
     */
    private Double latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubetagExtender1.CubeName
     *
     * @mbg.generated
     */
    private String cubeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubetagExtender1.CubeType
     *
     * @mbg.generated
     */
    private String cubeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubetagExtender1.MakeTime
     *
     * @mbg.generated
     */
    private Date makeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubetagExtender1.CubeState
     *
     * @mbg.generated
     */
    private Integer cubeState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubetagExtender1.Influence
     *
     * @mbg.generated
     */
    private Double influence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubetagExtender1.PlaceAddress
     *
     * @mbg.generated
     */
    private String placeAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubetagExtender1.AdministrativeArea
     *
     * @mbg.generated
     */
    private String administrativeArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubetagExtender1.Country
     *
     * @mbg.generated
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubetagExtender1.ActivationTime
     *
     * @mbg.generated
     */
    private Date activationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubetagExtender1.CubeHits
     *
     * @mbg.generated
     */
    private Integer cubeHits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubetagExtender1.CubeLikes
     *
     * @mbg.generated
     */
    private Integer cubeLikes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubetagExtender1.CubeDisLikes
     *
     * @mbg.generated
     */
    private Integer cubeDisLikes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubetagExtender1.CommentCount
     *
     * @mbg.generated
     */
    private Integer commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubetagExtender1.ContentValue
     *
     * @mbg.generated
     */
    private String contentValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubetagExtender1.cubeuuid
     *
     * @return the value of FcubetagExtender1.cubeuuid
     *
     * @mbg.generated
     */
    public String getCubeuuid() {
        return cubeuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubetagExtender1.cubeuuid
     *
     * @param cubeuuid the value for FcubetagExtender1.cubeuuid
     *
     * @mbg.generated
     */
    public void setCubeuuid(String cubeuuid) {
        this.cubeuuid = cubeuuid == null ? null : cubeuuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubetagExtender1.tagitem
     *
     * @return the value of FcubetagExtender1.tagitem
     *
     * @mbg.generated
     */
    public String getTagitem() {
        return tagitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubetagExtender1.tagitem
     *
     * @param tagitem the value for FcubetagExtender1.tagitem
     *
     * @mbg.generated
     */
    public void setTagitem(String tagitem) {
        this.tagitem = tagitem == null ? null : tagitem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubetagExtender1.Uid
     *
     * @return the value of FcubetagExtender1.Uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubetagExtender1.Uid
     *
     * @param uid the value for FcubetagExtender1.Uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubetagExtender1.longitude
     *
     * @return the value of FcubetagExtender1.longitude
     *
     * @mbg.generated
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubetagExtender1.longitude
     *
     * @param longitude the value for FcubetagExtender1.longitude
     *
     * @mbg.generated
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubetagExtender1.latitude
     *
     * @return the value of FcubetagExtender1.latitude
     *
     * @mbg.generated
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubetagExtender1.latitude
     *
     * @param latitude the value for FcubetagExtender1.latitude
     *
     * @mbg.generated
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubetagExtender1.CubeName
     *
     * @return the value of FcubetagExtender1.CubeName
     *
     * @mbg.generated
     */
    public String getCubeName() {
        return cubeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubetagExtender1.CubeName
     *
     * @param cubeName the value for FcubetagExtender1.CubeName
     *
     * @mbg.generated
     */
    public void setCubeName(String cubeName) {
        this.cubeName = cubeName == null ? null : cubeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubetagExtender1.CubeType
     *
     * @return the value of FcubetagExtender1.CubeType
     *
     * @mbg.generated
     */
    public String getCubeType() {
        return cubeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubetagExtender1.CubeType
     *
     * @param cubeType the value for FcubetagExtender1.CubeType
     *
     * @mbg.generated
     */
    public void setCubeType(String cubeType) {
        this.cubeType = cubeType == null ? null : cubeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubetagExtender1.MakeTime
     *
     * @return the value of FcubetagExtender1.MakeTime
     *
     * @mbg.generated
     */
    public Date getMakeTime() {
        return makeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubetagExtender1.MakeTime
     *
     * @param makeTime the value for FcubetagExtender1.MakeTime
     *
     * @mbg.generated
     */
    public void setMakeTime(Date makeTime) {
        this.makeTime = makeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubetagExtender1.CubeState
     *
     * @return the value of FcubetagExtender1.CubeState
     *
     * @mbg.generated
     */
    public Integer getCubeState() {
        return cubeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubetagExtender1.CubeState
     *
     * @param cubeState the value for FcubetagExtender1.CubeState
     *
     * @mbg.generated
     */
    public void setCubeState(Integer cubeState) {
        this.cubeState = cubeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubetagExtender1.Influence
     *
     * @return the value of FcubetagExtender1.Influence
     *
     * @mbg.generated
     */
    public Double getInfluence() {
        return influence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubetagExtender1.Influence
     *
     * @param influence the value for FcubetagExtender1.Influence
     *
     * @mbg.generated
     */
    public void setInfluence(Double influence) {
        this.influence = influence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubetagExtender1.PlaceAddress
     *
     * @return the value of FcubetagExtender1.PlaceAddress
     *
     * @mbg.generated
     */
    public String getPlaceAddress() {
        return placeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubetagExtender1.PlaceAddress
     *
     * @param placeAddress the value for FcubetagExtender1.PlaceAddress
     *
     * @mbg.generated
     */
    public void setPlaceAddress(String placeAddress) {
        this.placeAddress = placeAddress == null ? null : placeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubetagExtender1.AdministrativeArea
     *
     * @return the value of FcubetagExtender1.AdministrativeArea
     *
     * @mbg.generated
     */
    public String getAdministrativeArea() {
        return administrativeArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubetagExtender1.AdministrativeArea
     *
     * @param administrativeArea the value for FcubetagExtender1.AdministrativeArea
     *
     * @mbg.generated
     */
    public void setAdministrativeArea(String administrativeArea) {
        this.administrativeArea = administrativeArea == null ? null : administrativeArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubetagExtender1.Country
     *
     * @return the value of FcubetagExtender1.Country
     *
     * @mbg.generated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubetagExtender1.Country
     *
     * @param country the value for FcubetagExtender1.Country
     *
     * @mbg.generated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubetagExtender1.ActivationTime
     *
     * @return the value of FcubetagExtender1.ActivationTime
     *
     * @mbg.generated
     */
    public Date getActivationTime() {
        return activationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubetagExtender1.ActivationTime
     *
     * @param activationTime the value for FcubetagExtender1.ActivationTime
     *
     * @mbg.generated
     */
    public void setActivationTime(Date activationTime) {
        this.activationTime = activationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubetagExtender1.CubeHits
     *
     * @return the value of FcubetagExtender1.CubeHits
     *
     * @mbg.generated
     */
    public Integer getCubeHits() {
        return cubeHits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubetagExtender1.CubeHits
     *
     * @param cubeHits the value for FcubetagExtender1.CubeHits
     *
     * @mbg.generated
     */
    public void setCubeHits(Integer cubeHits) {
        this.cubeHits = cubeHits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubetagExtender1.CubeLikes
     *
     * @return the value of FcubetagExtender1.CubeLikes
     *
     * @mbg.generated
     */
    public Integer getCubeLikes() {
        return cubeLikes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubetagExtender1.CubeLikes
     *
     * @param cubeLikes the value for FcubetagExtender1.CubeLikes
     *
     * @mbg.generated
     */
    public void setCubeLikes(Integer cubeLikes) {
        this.cubeLikes = cubeLikes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubetagExtender1.CubeDisLikes
     *
     * @return the value of FcubetagExtender1.CubeDisLikes
     *
     * @mbg.generated
     */
    public Integer getCubeDisLikes() {
        return cubeDisLikes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubetagExtender1.CubeDisLikes
     *
     * @param cubeDisLikes the value for FcubetagExtender1.CubeDisLikes
     *
     * @mbg.generated
     */
    public void setCubeDisLikes(Integer cubeDisLikes) {
        this.cubeDisLikes = cubeDisLikes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubetagExtender1.CommentCount
     *
     * @return the value of FcubetagExtender1.CommentCount
     *
     * @mbg.generated
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubetagExtender1.CommentCount
     *
     * @param commentCount the value for FcubetagExtender1.CommentCount
     *
     * @mbg.generated
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubetagExtender1.ContentValue
     *
     * @return the value of FcubetagExtender1.ContentValue
     *
     * @mbg.generated
     */
    public String getContentValue() {
        return contentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubetagExtender1.ContentValue
     *
     * @param contentValue the value for FcubetagExtender1.ContentValue
     *
     * @mbg.generated
     */
    public void setContentValue(String contentValue) {
        this.contentValue = contentValue == null ? null : contentValue.trim();
    }
}