package com.wing.forutona.FcubeDto;

public class Mapfindscopestep {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MapFindScopeStep.idx
     *
     * @mbg.generated
     */
    private Integer idx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MapFindScopeStep.scopeMeter
     *
     * @mbg.generated
     */
    private Integer scopeMeter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MapFindScopeStep.idx
     *
     * @return the value of MapFindScopeStep.idx
     *
     * @mbg.generated
     */
    public Integer getIdx() {
        return idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MapFindScopeStep.idx
     *
     * @param idx the value for MapFindScopeStep.idx
     *
     * @mbg.generated
     */
    public void setIdx(Integer idx) {
        this.idx = idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MapFindScopeStep.scopeMeter
     *
     * @return the value of MapFindScopeStep.scopeMeter
     *
     * @mbg.generated
     */
    public Integer getScopeMeter() {
        return scopeMeter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MapFindScopeStep.scopeMeter
     *
     * @param scopeMeter the value for MapFindScopeStep.scopeMeter
     *
     * @mbg.generated
     */
    public void setScopeMeter(Integer scopeMeter) {
        this.scopeMeter = scopeMeter;
    }


}