package com.wing.forutona.FcubeDto;

import java.util.Date;

public class Pleyerjoincube {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PleyerJoinCube.Cubeuuid
     *
     * @mbg.generated
     */
    private String cubeuuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PleyerJoinCube.MakerUid
     *
     * @mbg.generated
     */
    private String makerUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PleyerJoinCube.longitude
     *
     * @mbg.generated
     */
    private Double longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PleyerJoinCube.latitude
     *
     * @mbg.generated
     */
    private Double latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PleyerJoinCube.CubeName
     *
     * @mbg.generated
     */
    private String cubeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PleyerJoinCube.CubeType
     *
     * @mbg.generated
     */
    private String cubeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PleyerJoinCube.MakeTime
     *
     * @mbg.generated
     */
    private Date makeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PleyerJoinCube.PlaceAddress
     *
     * @mbg.generated
     */
    private String placeAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PleyerJoinCube.NaPoint
     *
     * @mbg.generated
     */
    private Double naPoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PleyerJoinCube.YouPoint
     *
     * @mbg.generated
     */
    private Double youPoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PleyerJoinCube.PointReward
     *
     * @mbg.generated
     */
    private Double pointReward;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PleyerJoinCube.InfluenceReward
     *
     * @mbg.generated
     */
    private Double influenceReward;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PleyerJoinCube.ActivationTime
     *
     * @mbg.generated
     */
    private Date activationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PleyerJoinCube.CubeHits
     *
     * @mbg.generated
     */
    private Integer cubeHits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PleyerJoinCube.CubeLikes
     *
     * @mbg.generated
     */
    private Integer cubeLikes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PleyerJoinCube.CubeDisLikes
     *
     * @mbg.generated
     */
    private Integer cubeDisLikes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PleyerJoinCube.CommentCount
     *
     * @mbg.generated
     */
    private Integer commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PleyerJoinCube.UserExp
     *
     * @mbg.generated
     */
    private Double userExp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PleyerJoinCube.PlayerUid
     *
     * @mbg.generated
     */
    private String playerUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PleyerJoinCube.StartTime
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PleyerJoinCube.ContentType
     *
     * @mbg.generated
     */
    private String contentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PleyerJoinCube.MakerLevel
     *
     * @mbg.generated
     */
    private Double makerLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PleyerJoinCube.MakerProfilePicktureUrl
     *
     * @mbg.generated
     */
    private String makerProfilePicktureUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PleyerJoinCube.MakerNickName
     *
     * @mbg.generated
     */
    private String makerNickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PleyerJoinCube.ContentValue
     *
     * @mbg.generated
     */
    private String contentValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PleyerJoinCube.Cubeuuid
     *
     * @return the value of PleyerJoinCube.Cubeuuid
     *
     * @mbg.generated
     */
    public String getCubeuuid() {
        return cubeuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PleyerJoinCube.Cubeuuid
     *
     * @param cubeuuid the value for PleyerJoinCube.Cubeuuid
     *
     * @mbg.generated
     */
    public void setCubeuuid(String cubeuuid) {
        this.cubeuuid = cubeuuid == null ? null : cubeuuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PleyerJoinCube.MakerUid
     *
     * @return the value of PleyerJoinCube.MakerUid
     *
     * @mbg.generated
     */
    public String getMakerUid() {
        return makerUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PleyerJoinCube.MakerUid
     *
     * @param makerUid the value for PleyerJoinCube.MakerUid
     *
     * @mbg.generated
     */
    public void setMakerUid(String makerUid) {
        this.makerUid = makerUid == null ? null : makerUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PleyerJoinCube.longitude
     *
     * @return the value of PleyerJoinCube.longitude
     *
     * @mbg.generated
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PleyerJoinCube.longitude
     *
     * @param longitude the value for PleyerJoinCube.longitude
     *
     * @mbg.generated
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PleyerJoinCube.latitude
     *
     * @return the value of PleyerJoinCube.latitude
     *
     * @mbg.generated
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PleyerJoinCube.latitude
     *
     * @param latitude the value for PleyerJoinCube.latitude
     *
     * @mbg.generated
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PleyerJoinCube.CubeName
     *
     * @return the value of PleyerJoinCube.CubeName
     *
     * @mbg.generated
     */
    public String getCubeName() {
        return cubeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PleyerJoinCube.CubeName
     *
     * @param cubeName the value for PleyerJoinCube.CubeName
     *
     * @mbg.generated
     */
    public void setCubeName(String cubeName) {
        this.cubeName = cubeName == null ? null : cubeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PleyerJoinCube.CubeType
     *
     * @return the value of PleyerJoinCube.CubeType
     *
     * @mbg.generated
     */
    public String getCubeType() {
        return cubeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PleyerJoinCube.CubeType
     *
     * @param cubeType the value for PleyerJoinCube.CubeType
     *
     * @mbg.generated
     */
    public void setCubeType(String cubeType) {
        this.cubeType = cubeType == null ? null : cubeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PleyerJoinCube.MakeTime
     *
     * @return the value of PleyerJoinCube.MakeTime
     *
     * @mbg.generated
     */
    public Date getMakeTime() {
        return makeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PleyerJoinCube.MakeTime
     *
     * @param makeTime the value for PleyerJoinCube.MakeTime
     *
     * @mbg.generated
     */
    public void setMakeTime(Date makeTime) {
        this.makeTime = makeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PleyerJoinCube.PlaceAddress
     *
     * @return the value of PleyerJoinCube.PlaceAddress
     *
     * @mbg.generated
     */
    public String getPlaceAddress() {
        return placeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PleyerJoinCube.PlaceAddress
     *
     * @param placeAddress the value for PleyerJoinCube.PlaceAddress
     *
     * @mbg.generated
     */
    public void setPlaceAddress(String placeAddress) {
        this.placeAddress = placeAddress == null ? null : placeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PleyerJoinCube.NaPoint
     *
     * @return the value of PleyerJoinCube.NaPoint
     *
     * @mbg.generated
     */
    public Double getNaPoint() {
        return naPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PleyerJoinCube.NaPoint
     *
     * @param naPoint the value for PleyerJoinCube.NaPoint
     *
     * @mbg.generated
     */
    public void setNaPoint(Double naPoint) {
        this.naPoint = naPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PleyerJoinCube.YouPoint
     *
     * @return the value of PleyerJoinCube.YouPoint
     *
     * @mbg.generated
     */
    public Double getYouPoint() {
        return youPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PleyerJoinCube.YouPoint
     *
     * @param youPoint the value for PleyerJoinCube.YouPoint
     *
     * @mbg.generated
     */
    public void setYouPoint(Double youPoint) {
        this.youPoint = youPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PleyerJoinCube.PointReward
     *
     * @return the value of PleyerJoinCube.PointReward
     *
     * @mbg.generated
     */
    public Double getPointReward() {
        return pointReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PleyerJoinCube.PointReward
     *
     * @param pointReward the value for PleyerJoinCube.PointReward
     *
     * @mbg.generated
     */
    public void setPointReward(Double pointReward) {
        this.pointReward = pointReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PleyerJoinCube.InfluenceReward
     *
     * @return the value of PleyerJoinCube.InfluenceReward
     *
     * @mbg.generated
     */
    public Double getInfluenceReward() {
        return influenceReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PleyerJoinCube.InfluenceReward
     *
     * @param influenceReward the value for PleyerJoinCube.InfluenceReward
     *
     * @mbg.generated
     */
    public void setInfluenceReward(Double influenceReward) {
        this.influenceReward = influenceReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PleyerJoinCube.ActivationTime
     *
     * @return the value of PleyerJoinCube.ActivationTime
     *
     * @mbg.generated
     */
    public Date getActivationTime() {
        return activationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PleyerJoinCube.ActivationTime
     *
     * @param activationTime the value for PleyerJoinCube.ActivationTime
     *
     * @mbg.generated
     */
    public void setActivationTime(Date activationTime) {
        this.activationTime = activationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PleyerJoinCube.CubeHits
     *
     * @return the value of PleyerJoinCube.CubeHits
     *
     * @mbg.generated
     */
    public Integer getCubeHits() {
        return cubeHits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PleyerJoinCube.CubeHits
     *
     * @param cubeHits the value for PleyerJoinCube.CubeHits
     *
     * @mbg.generated
     */
    public void setCubeHits(Integer cubeHits) {
        this.cubeHits = cubeHits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PleyerJoinCube.CubeLikes
     *
     * @return the value of PleyerJoinCube.CubeLikes
     *
     * @mbg.generated
     */
    public Integer getCubeLikes() {
        return cubeLikes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PleyerJoinCube.CubeLikes
     *
     * @param cubeLikes the value for PleyerJoinCube.CubeLikes
     *
     * @mbg.generated
     */
    public void setCubeLikes(Integer cubeLikes) {
        this.cubeLikes = cubeLikes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PleyerJoinCube.CubeDisLikes
     *
     * @return the value of PleyerJoinCube.CubeDisLikes
     *
     * @mbg.generated
     */
    public Integer getCubeDisLikes() {
        return cubeDisLikes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PleyerJoinCube.CubeDisLikes
     *
     * @param cubeDisLikes the value for PleyerJoinCube.CubeDisLikes
     *
     * @mbg.generated
     */
    public void setCubeDisLikes(Integer cubeDisLikes) {
        this.cubeDisLikes = cubeDisLikes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PleyerJoinCube.CommentCount
     *
     * @return the value of PleyerJoinCube.CommentCount
     *
     * @mbg.generated
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PleyerJoinCube.CommentCount
     *
     * @param commentCount the value for PleyerJoinCube.CommentCount
     *
     * @mbg.generated
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PleyerJoinCube.UserExp
     *
     * @return the value of PleyerJoinCube.UserExp
     *
     * @mbg.generated
     */
    public Double getUserExp() {
        return userExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PleyerJoinCube.UserExp
     *
     * @param userExp the value for PleyerJoinCube.UserExp
     *
     * @mbg.generated
     */
    public void setUserExp(Double userExp) {
        this.userExp = userExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PleyerJoinCube.PlayerUid
     *
     * @return the value of PleyerJoinCube.PlayerUid
     *
     * @mbg.generated
     */
    public String getPlayerUid() {
        return playerUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PleyerJoinCube.PlayerUid
     *
     * @param playerUid the value for PleyerJoinCube.PlayerUid
     *
     * @mbg.generated
     */
    public void setPlayerUid(String playerUid) {
        this.playerUid = playerUid == null ? null : playerUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PleyerJoinCube.StartTime
     *
     * @return the value of PleyerJoinCube.StartTime
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PleyerJoinCube.StartTime
     *
     * @param startTime the value for PleyerJoinCube.StartTime
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PleyerJoinCube.ContentType
     *
     * @return the value of PleyerJoinCube.ContentType
     *
     * @mbg.generated
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PleyerJoinCube.ContentType
     *
     * @param contentType the value for PleyerJoinCube.ContentType
     *
     * @mbg.generated
     */
    public void setContentType(String contentType) {
        this.contentType = contentType == null ? null : contentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PleyerJoinCube.MakerLevel
     *
     * @return the value of PleyerJoinCube.MakerLevel
     *
     * @mbg.generated
     */
    public Double getMakerLevel() {
        return makerLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PleyerJoinCube.MakerLevel
     *
     * @param makerLevel the value for PleyerJoinCube.MakerLevel
     *
     * @mbg.generated
     */
    public void setMakerLevel(Double makerLevel) {
        this.makerLevel = makerLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PleyerJoinCube.MakerProfilePicktureUrl
     *
     * @return the value of PleyerJoinCube.MakerProfilePicktureUrl
     *
     * @mbg.generated
     */
    public String getMakerProfilePicktureUrl() {
        return makerProfilePicktureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PleyerJoinCube.MakerProfilePicktureUrl
     *
     * @param makerProfilePicktureUrl the value for PleyerJoinCube.MakerProfilePicktureUrl
     *
     * @mbg.generated
     */
    public void setMakerProfilePicktureUrl(String makerProfilePicktureUrl) {
        this.makerProfilePicktureUrl = makerProfilePicktureUrl == null ? null : makerProfilePicktureUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PleyerJoinCube.MakerNickName
     *
     * @return the value of PleyerJoinCube.MakerNickName
     *
     * @mbg.generated
     */
    public String getMakerNickName() {
        return makerNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PleyerJoinCube.MakerNickName
     *
     * @param makerNickName the value for PleyerJoinCube.MakerNickName
     *
     * @mbg.generated
     */
    public void setMakerNickName(String makerNickName) {
        this.makerNickName = makerNickName == null ? null : makerNickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PleyerJoinCube.ContentValue
     *
     * @return the value of PleyerJoinCube.ContentValue
     *
     * @mbg.generated
     */
    public String getContentValue() {
        return contentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PleyerJoinCube.ContentValue
     *
     * @param contentValue the value for PleyerJoinCube.ContentValue
     *
     * @mbg.generated
     */
    public void setContentValue(String contentValue) {
        this.contentValue = contentValue == null ? null : contentValue.trim();
    }
}