spring:
  profiles:
    active: '@spring.profiles.active@'
---
spring:
  profiles: local
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  mvc:
    async:
      request-timeout: -1
server:
  port: 8443
forutona:
  serviekeypath: C:\\Users\\backho\\Desktop\\forutonadata\\adminsdkservicekey\\forutona-firebase-adminsdk-p6ho6-ab85124646.json
  storgeserviekeypath: C:\\Users\\backho\\Desktop\\forutonadata\\adminsdkservicekey\\Forutona-3539edf2b36d.json
  smssretrieverappsign: yEPaqsYH4k7
  sureMID: forutona1020
  sureMdeptcode: P8-ECX-6T
  sureMFrom: 010-6710-7004
logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
---
spring:
  profiles: real
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    async:
      request-timeout: -1

server:
  port: 8443
forutona:
  serviekeypath: /home/forutona/servicekeys/forutona-firebase-adminsdk-p6ho6-ab85124646.json
  storgeserviekeypath: /home/forutona/servicekeys/Forutona-3539edf2b36d.json
  smssretrieverappsign: DnCuZoNCCGH
  sureMID: forutona1020
  sureMdeptcode: P8-ECX-6T
  sureMFrom: 010-6710-7004
---
spring:
  profiles: test
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  mvc:
    async:
      request-timeout: -1
server:
  port: 8443
forutona:
  serviekeypath: C:\\Users\\backho\\Desktop\\forutonadata\\adminsdkservicekey\\forutona-firebase-adminsdk-p6ho6-ab85124646.json
  storgeserviekeypath: C:\\Users\\backho\\Desktop\\forutonadata\\adminsdkservicekey\\Forutona-3539edf2b36d.json
  smssretrieverappsign: hVwMMiFZJlz
  sureMID: forutona1020
  sureMdeptcode: P8-ECX-6T
  sureMFrom: 010-6710-7004
logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
---
spring:
  profiles: realtest
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    async:
      request-timeout: -1

server:
  port: 8443
forutona:
  serviekeypath: /home/forutona/servicekeys/forutona-firebase-adminsdk-p6ho6-ab85124646.json
  storgeserviekeypath: /home/forutona/servicekeys/Forutona-3539edf2b36d.json
  smssretrieverappsign: DnCuZoNCCGH
  sureMID: forutona1020
  sureMdeptcode: P8-ECX-6T
  sureMFrom: 010-6710-7004
---