package com.wing.forutona.AuthDao;

import com.wing.forutona.AuthDto.Phoneauthtable;
import java.util.List;

public interface PhoneauthtableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PhoneAuthTable
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PhoneAuthTable
     *
     * @mbg.generated
     */
    int insert(Phoneauthtable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PhoneAuthTable
     *
     * @mbg.generated
     */
    Phoneauthtable selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PhoneAuthTable
     *
     * @mbg.generated
     */
    List<Phoneauthtable> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PhoneAuthTable
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Phoneauthtable record);
}