package com.wing.forutona.AuthDao;

import com.wing.forutona.AuthDto.Userexppointhistroy;
import java.util.List;

public interface UserexppointhistroyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserExpPointHistroy
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer idx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserExpPointHistroy
     *
     * @mbg.generated
     */
    int insert(Userexppointhistroy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserExpPointHistroy
     *
     * @mbg.generated
     */
    Userexppointhistroy selectByPrimaryKey(Integer idx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserExpPointHistroy
     *
     * @mbg.generated
     */
    List<Userexppointhistroy> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserExpPointHistroy
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Userexppointhistroy record);

    double getCubeuuidGetPoint(Userexppointhistroy item);
}